# Generated by Django 5.1.2 on 2025-02-27 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EStudyApp', '0031_remove_question_update_at_flashcard_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSetBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('audio', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('from_ques', models.IntegerField(blank=True, null=True)),
                ('to_ques', models.IntegerField(blank=True, null=True)),
                ('part_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_description_question_set_bank', to='EStudyApp.partdescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('difficulty_level', models.CharField(blank=True, choices=[('BASIC', 'Basic'), ('MEDIUM', 'Medium'), ('DIFFICULTY', 'Difficulty'), ('VERY_DIFFICULTY', 'Very Difficulty')], default='', max_length=30, null=True)),
                ('correct_answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=10, null=True)),
                ('question_number', models.IntegerField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('part_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_description_question_bank', to='EStudyApp.partdescription')),
                ('question_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_question_type', to='EStudyApp.questiontype')),
                ('question_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_question_set_bank', to='question_bank.questionsetbank')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
