# Generated by Django 5.1.2 on 2025-03-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0002_alter_questionsetbank_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsetbank',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
