services:
  postgres:
    image: postgres:16.4-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - toeic-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - django-network

  # api: 
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   ports: 
  #     - 8080:8000
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #   networks:
  #     - django-network

networks:
  django-network:
    driver: bridge

volumes:
  toeic-db:
