# Generated by Django 5.1.2 on 2024-12-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_info_alter_course_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
