# Generated by Django 5.1.2 on 2024-12-17 19:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
