# Generated by Django 5.1.2 on 2024-12-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_blog_questions_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='part_info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
