# Generated by Django 5.1.2 on 2024-12-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_blog_part_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='from_ques',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='to_ques',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
