# Generated by Django 5.1.2 on 2024-12-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_blog_from_ques_blog_to_ques'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
