# Generated by Django 5.1.2 on 2024-12-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_blog_author_alter_commentblog_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewlesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
