# Generated by Django 5.1.2 on 2024-12-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_blog_deleted_at_commentblog_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
