# Generated by Django 5.1.2 on 2025-01-01 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_remove_blog_publish_date_blog_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlesson',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='course.reviewlesson'),
        ),
    ]
