# Generated by Django 5.1.2 on 2025-01-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='star',
        ),
    ]
