# Generated by Django 5.1.2 on 2024-11-04 14:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=10)),
                ('part_description', models.TextField(blank=True, null=True)),
                ('skill', models.CharField(blank=True, choices=[('READING', 'Reading'), ('LISTENING', 'Listening')], max_length=30, null=True)),
                ('quantity', models.IntegerField(blank=True, choices=[(6, 'PART_1'), (25, 'PART_2'), (39, 'PART_3'), (30, 'PART_4'), (30, 'PART_5'), (16, 'PART_6'), (54, 'PART_7')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type_test', models.CharField(blank=True, choices=[('READING', 'Reading'), ('LISTENING', 'Listening')], max_length=30, null=True)),
                ('test_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('duration', models.DurationField(blank=True, default=datetime.timedelta(seconds=7200), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_part_description', to='EStudyApp.partdescription')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_test', to='EStudyApp.test')),
            ],
        ),
        migrations.CreateModel(
            name='PartQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partquestionset_part', to='EStudyApp.part')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partquestionset_question_set', to='EStudyApp.questionset')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('BASIC', 'Basic'), ('MEDIUM', 'Medium'), ('DIFFICULTY', 'Difficulty'), ('VERY_DIFFICULTY', 'Very Difficulty')], default=('BASIC', 'Basic'), max_length=30)),
                ('correct_answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=10, null=True)),
                ('question_number', models.IntegerField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_question_set', to='EStudyApp.questionset')),
                ('question_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_question_type', to='EStudyApp.questiontype')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('correct_answers', models.IntegerField(blank=True, null=True)),
                ('wrong_answers', models.IntegerField(blank=True, null=True)),
                ('unanswer_questions', models.IntegerField(blank=True, null=True)),
                ('percentage_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('listening_score', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('reading_score', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('test_result', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_user', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_test', to='EStudyApp.test')),
            ],
        ),
    ]
