# Generated by Django 5.1.2 on 2024-11-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EStudyApp', '0003_alter_question_difficulty_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiontype',
            old_name='type_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='test_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='type_test',
            new_name='type',
        ),
    ]
