# Generated by Django 5.1.2 on 2024-11-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EStudyApp', '0007_remove_test_part_count_remove_test_question_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='part_count',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='test',
            name='question_count',
            field=models.IntegerField(default=200),
        ),
    ]
