# Generated by Django 5.1.2 on 2024-12-04 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EStudyApp', '0009_state_tag_historytraining_test_tag_testcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_test', to='EStudyApp.test'),
        ),
        migrations.AddField(
            model_name='state',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
