# Generated by Django 5.1.2 on 2024-12-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EStudyApp', '0011_state_initial_minutes_state_initial_seconds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historytraining',
            name='part',
        ),
        migrations.AddField(
            model_name='historytraining',
            name='part_list',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
