# Generated by Django 5.1.2 on 2024-12-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EStudyApp', '0012_remove_historytraining_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
