# Generated by Django 5.1.2 on 2024-12-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EStudyApp', '0018_alter_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('practice', 'Practice'), ('all', 'All')], max_length=30, null=True),
        ),
    ]
