# Generated by Django 5.1.2 on 2024-12-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EStudyApp', '0020_alter_test_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='type',
            new_name='types',
        ),
    ]
