# Generated by Django 5.1.2 on 2024-12-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EStudyApp', '0021_rename_type_test_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentblog',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='commentblog',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='commentblog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commentlesson',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='commentlesson',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='commentlesson',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='CommentBlog',
        ),
        migrations.DeleteModel(
            name='CommentLesson',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
