# Generated by Django 5.1.2 on 2024-12-20 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EStudyApp', '0023_test_created_at_test_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='part_part_description', to='EStudyApp.partdescription'),
        ),
        migrations.AlterField(
            model_name='part',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='part_test', to='EStudyApp.test'),
        ),
    ]
