# Generated by Django 5.1.2 on 2024-12-20 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EStudyApp', '0025_alter_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_part_description', to='EStudyApp.partdescription'),
        ),
    ]
