# Generated by Django 5.1.2 on 2024-12-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EStudyApp', '0027_questionset_from_ques'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='to_ques',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
