# Generated by Django 5.1.2 on 2024-12-23 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EStudyApp', '0028_questionset_to_ques'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='history',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_test', to='EStudyApp.test'),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historytraining',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_test', to='EStudyApp.test'),
        ),
        migrations.AlterField(
            model_name='historytraining',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_part_description', to='EStudyApp.partdescription'),
        ),
        migrations.AlterField(
            model_name='partquestionset',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partquestionset_part', to='EStudyApp.part'),
        ),
        migrations.AlterField(
            model_name='partquestionset',
            name='question_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partquestionset_question_set', to='EStudyApp.questionset'),
        ),
        migrations.AlterField(
            model_name='testcomment',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testcomment_test', to='EStudyApp.test'),
        ),
        migrations.AlterField(
            model_name='testcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testcomment_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
