# Generated by Django 5.1.2 on 2024-12-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EStudyApp', '0029_alter_flashcard_user_alter_history_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partdescription',
            name='part_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
