# Generated by Django 5.1.2 on 2024-12-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EStudyApp', '0030_partdescription_part_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
