# Generated by Django 5.1.2 on 2025-03-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EStudyApp', '0032_alter_questionset_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='tag',
        ),
        migrations.AddField(
            model_name='test',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tests', to='EStudyApp.tag'),
        ),
    ]
