# Generated by Django 5.1.2 on 2025-03-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EStudyApp', '0033_remove_test_tag_test_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='closeDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='publishDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
