# Generated by Django 5.1.2 on 2025-03-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EStudyApp', '0035_rename_closedate_test_close_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=125, null=True, unique=True),
        ),
    ]
