# Generated by Django 5.1.7 on 2025-04-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EStudyApp', '0036_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
