# Generated by Django 5.1.2 on 2024-12-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('teacher', 'Teacher'), ('student', 'Student')], default='user', max_length=20),
        ),
    ]
