# Generated by Django 5.1.7 on 2025-09-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_jti',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
